### ISSUE TITLE
sidekiq dead set functionality is broken

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#1071]
<img width="864" alt="Screen Shot 2022-08-29 at 9 54 41 AM" src="https://user-images.githubusercontent.com/35935196/187217741-78e02f11-ac91-44d5-a690-e1d7d8c561c6.png">

the yield here: [app/models/api_resource.rb:80](https://github.com/restarone/violet_rails/blob/master/app/models/api_resource.rb#L80) is causing sidekiq jobs to get stuck in a `failed` state -- this should not be the case. We should instead see the jobs show up under `dead`. `Failed` is simply a transitive state. 

https://github.com/mperham/sidekiq/issues/2760#issuecomment-170112610

**Comment by Pralish** [comment]
@donrestarone , Can you confirm if the stuck jobs are actually api_actions stuck in 'executing' state?

**Comment by donrestarone** [comment]
@Pralish yup! They are stuck in "executing" state
