### ISSUE TITLE
Cannot create a new layout

### ISSUE THREAD

**Issue by Ayon95** [restarone/violet_rails#1089]
**Describe the bug**
Getting an error when trying to create a new layout.

**To Reproduce**
1. Go to 'Layouts'
2. Click on 'Create New Layout'

**Expected behavior**
A page to create a new layout should appear.

**Screenshots**
![screencapture-lvh-me-5250-admin-sites-1-layouts-new-2022-09-09-18_08_45](https://user-images.githubusercontent.com/73725297/189452521-1795856a-076e-4911-a9c5-a2e9a8e85a6e.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 105.0.5195.102

**Comment by donrestarone** [comment]
I can reproduce on my Mac locally as well. A few things to note: 

1. `test/controllers/admin/comfy/layouts_controller_test.rb` does not include a test for `new_comfy_admin_cms_site_layout_path` so we don't have test coverage for the `/admin/sites/:site_id/layouts/new` action that hits the controller endpoint `comfy/admin/cms/layouts#new`
2. We will need to add a test case that covers the gap in testing mentioned above
3. worth noting in our fork of the CMS, we allow all parameters through (https://github.com/restarone/comfortable-mexican-sofa/blob/master/app/controllers/comfy/admin/cms/layouts_controller.rb#L66) -- this is different to the customization we have applied in Violet Rails: https://github.com/restarone/violet_rails/blob/master/app/controllers/comfy/admin/cms/layouts_controller.rb#L70

**Comment by donrestarone** [comment]
in production, this issue manifests as a white screen on safari or a broken page in chrome:

<img width="1728" alt="Screen Shot 2022-09-09 at 6 48 54 PM" src="https://user-images.githubusercontent.com/35935196/189455760-fb81ea77-2c20-4eb9-9b5e-84d1395f0360.png">
<img width="1728" alt="Screen Shot 2022-09-09 at 6 47 41 PM" src="https://user-images.githubusercontent.com/35935196/189455769-d4b36a61-adde-475b-925b-090ada395d56.png">
