### ISSUE TITLE
Cannot create an API resource with a large MP4 video from admin

### ISSUE THREAD

**Issue by Ayon95** [restarone/violet_rails#1112]
**Describe the bug**
A black page with an error message appears after 4-5 minutes when trying to create an API resource with an MP4 video (file size 240 MB).

**To Reproduce**
1. Go to 'API'
2. Create an API namespace with a non-primitive property of type `file`
3. Click on the button to create a new API resource
4. Upload a video

**Expected behavior**
An API resource with a video can be created

**Screenshots**
Error:
![Capture](https://user-images.githubusercontent.com/73725297/190510470-633c275b-b942-4483-80e3-020636fb22c7.PNG)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 105.0.5195.102

**Comment by donrestarone** [comment]
A possible fix would be to implement a javascript based uploader (see Admin > Files > new upload) 

Currently we are using an input field for the upload which limits the upload size to the HTTP timeout.
