### ISSUE TITLE
No file upload validation is done in Graphics section - User is able to upload any type of file

### ISSUE THREAD

**Issue by kripananda-yadav** [restarone/violet_rails#1161]
**Describe the bug**
User is able to upload any type of file with extension like .exe, .tif etc. and also the upload size restriction is  not performed as user is able to upload file of any size due to which the company logo is not show as user is allowed to upload any kind of file.

**To Reproduce**
1. Navigate to Violet Rails Admin  page
2. Click on  'APP SETTINGS' Sub Menu
3. Scroll down to 'GRAPHICS section
4. Click on 'Choose files'  of "COMPANY LOGO" in an attempt to add files.
5. Add file with extension .exe with size of 500MB
<img width="469" alt="image" src="https://user-images.githubusercontent.com/70195786/195997553-78fc6b6d-4053-41eb-ae26-6aae849422ca.png">

7. File will be uploaded
<img width="296" alt="image" src="https://user-images.githubusercontent.com/70195786/195997647-f244f093-5e01-49bf-ba2b-18cff11f848c.png">

9.  Scroll down to bottom of the page
10. click on the save button

**Expected behavior**
In  COMPANY LOGO section of File upload only files with extension .jpg or .jpeg must be allowed with proper restriction of the size (for eg 10MB ) and also after the file has been successfully uploaded it should be reflected on the associated places. 

**Screenshots**
<img width="702" alt="image" src="https://user-images.githubusercontent.com/70195786/195997715-8c7dc175-d835-4345-844f-2db8f581773a.png">

<img width="474" alt="image" src="https://user-images.githubusercontent.com/70195786/195997755-0ec97ae1-f109-4013-aea6-6e2441c074fa.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version:  106.0.5249.119

**Additional context**
If user is allowed to upload file of any size then server storage might get full in no time.

**Comment by donrestarone** [comment]
@kripananda-yadav Did you setup the app locally, If so which guide did you follow?

**Comment by kripananda-yadav** [comment]
@donrestarone Yes I have setup the app locally. I got a link (https://github.com/restarone/violet_rails/wiki/Getting-started-(development-cheatsheet)) getting started with development from readme.md.
