### ISSUE TITLE
Social-sharing metadata for API HTML renderer

### ISSUE THREAD

**Issue by Ayon95** [restarone/violet_rails#1166]
When a show/details page is shared on social media, no information about that page is shown. Social-sharing metadata needs to be included when these pages are shared.

A details page:
![story-details-page](https://user-images.githubusercontent.com/73725297/196473826-d8a63be6-d66a-46bd-950e-a472a1745da7.PNG)

No metadata is shown:
![no-metadata](https://user-images.githubusercontent.com/73725297/196474617-fb08cb9d-8ac3-48f1-9f3f-09dc9fffb377.jpg)

**Comment by donrestarone** [comment]
The requirement is to add a **Social Share Preview** pane to the API Namespace #Show view
<img width="1728" alt="Screen Shot 2022-10-22 at 7 33 50 AM" src="https://user-images.githubusercontent.com/35935196/197336843-5060f17e-8e31-4d12-92d3-e7645617cb41.png">

This view will allow the user to define the mapping for the OG specification by selecting which OG attributes map to the API Namespace attribute

<img width="1728" alt="Screen Shot 2022-10-22 at 7 33 40 AM" src="https://user-images.githubusercontent.com/35935196/197336894-11b9ed5b-c15f-499e-bc6c-2907a3f519c1.png">


see here for our current OG implementation, its used in the CMS at a global level: https://github.com/restarone/violet_rails/blob/master/app/views/shared/_meta_tags.html.erb#L1-L22


For each of the fields above we will need a form field that will help us define the mapping for each of the OG attributes: 

ex; 

``` ruby
og: {
                        image: og_image,
                        title: html_title(Subdomain.current),
                        description: site_description(Subdomain.current)
                      },
```
will be mapped to

``` ruby
og: {
                        image: api_resource.non_primitive_type[:video_thumbnail],
                        title: api_resource.properties[:title],
                        description: api_resource.properties[:description]
                      },
```
