### ISSUE TITLE
social share mapping not working for nikean

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#1199]
**Describe the bug**
social share works on testnet but not on Nikean.org (eg: https://nikean.org/story-details?id=1404414)
<img width="772" alt="Screen Shot 2022-11-02 at 7 58 29 PM" src="https://user-images.githubusercontent.com/35935196/199624251-8a834d6a-d476-407e-a333-abf4fc3012dd.png">

**To Reproduce**

Share a link to a HTML API renderer video (eg: https://nikean.org/story-details?id=1404414)

<img width="1728" alt="Screen Shot 2022-11-02 at 7 58 39 PM" src="https://user-images.githubusercontent.com/35935196/199624247-5cc31b0a-a15d-40bb-b488-9998272d5532.png">

<img width="1728" alt="Screen Shot 2022-11-02 at 8 34 14 PM" src="https://user-images.githubusercontent.com/35935196/199627218-13880931-ccc7-49b4-b13d-8f1de628e25d.png">

<img width="1728" alt="Screen Shot 2022-11-02 at 8 34 03 PM" src="https://user-images.githubusercontent.com/35935196/199627225-4b019665-99f9-4ac8-b694-6c8d1664bf39.png">

**Comment by Pralish** [comment]
# RCA

Api html renderer and Api forms both use `@api_namespace` instance variable. Nikean uses both api form and api html renderer on same page. @api_namespace from api form is overriding the api_namespace in api html renderer.

FIX: https://github.com/restarone/violet_rails/pull/1227
