### ISSUE TITLE
Snippets not working in cookie consent on Ordinary Trip.

### ISSUE THREAD

**Issue by westernal** [restarone/violet_rails#1213]
**Describe the bug**
When you add snippets to the cookie consent section it doesn't work and instead of the link or image or etc. it just shows the snippet's syntax:
![image](https://user-images.githubusercontent.com/79543272/201202668-ec0c82a4-bfa4-43f9-b688-f579ecbf019e.png)
![image](https://user-images.githubusercontent.com/79543272/201203881-154b4b79-5422-4e47-bb86-1134e6058b53.png)

**To Reproduce**
Add any snippets like: {{ cms:file_link 57 }} to the cookie consent UI section.

**Comment by donrestarone** [comment]
@ajaystha42 can you look into this? If you want to pair, @Pralish and @alis-khadka have worked on the snippet renderer before
