### ISSUE TITLE
Video playback issue on Nikean story platform

### ISSUE THREAD

**Issue by Ayon95** [restarone/violet_rails#1242]
Issues:
- some videos are stopping halfway through
- if a video is paused briefly, it won't resume

These issues are happening in Safari. One possible reason could be that the server that serves the video files is not configured to support byte-range requests. Safari sends HTTP range requests in order to load videos in chunks and expects a 206 response from the server.

https://stackoverflow.com/questions/32996396/safari-9-0-can-not-play-mp4-video-on-the-storage-server
https://stackoverflow.com/questions/33744633/safari-not-loading-html5-video-in-rails-app
https://blog.logrocket.com/streaming-video-in-safari/

**Comment by donrestarone** [comment]
original thread on the client's forum: https://nikean.org/forum/threads/small-video-edits-playback-issue-cookies-issue
