### ISSUE TITLE
auto-doc in API Render Tab is wrong

### ISSUE THREAD

**Issue by restarone-solutions** [restarone/violet_rails#1355]
Steps to replicate.

**To Reproduce**
1. Create a namespace from admin panel > API > Create new namespace
2. Go to rendering tab inside the API Namespace
3. Suppose the API Namespace is `cocktails`.
4. API HTML Renderer index snippet is wrong there.

<img width="891" alt="Screenshot 2023-01-13 at 15 13 30" src="https://user-images.githubusercontent.com/101986515/212361726-18419e91-cc2a-41be-a7bf-ba42b30bf3dc.png">

it should actually be `render_api_namespace_resource_index`

**Comment by donrestarone** [comment]
affecting sipshucksip.com
