### ISSUE TITLE
Ability to query API resources that match any or multiple words of a search term

### ISSUE THREAD

**Issue by Ayon95** [restarone/violet_rails#1374]
Currently, it is not possible to implement a keyword-based search. For example, if "professional development" is searched, a partial-match query does not return results for "professional" and/or "development". It tries to match "professional development" entirely.

This the query that I've attempted to use to implement a keyword-based search:
https://github.com/restarone/violet_rails/blob/master/test/models/concerns/jsonb_search/query_builder_test.rb#L33

**Comment by donrestarone** [comment]
adding a bit more detail: 

<img width="1490" alt="Screen Shot 2023-01-20 at 8 56 00 AM" src="https://user-images.githubusercontent.com/35935196/213714073-c717ae69-8799-45ee-9648-245a4725ba8c.png">

we want the system to given a query like "Professional Development" and have the ability to search for keywords (in this case, delineated by spaces) like "Professional" and "Development"  and show results that include "Professional" and/or "Development"
