### ISSUE TITLE
Cannot change account email from user settings

### ISSUE THREAD

**Issue by Ayon95** [restarone/violet_rails#1375]
**Describe the bug**
When I open the link to confirm account email change, an "Invalid token error" is shown

**To Reproduce**
1. Go to 'My Settings'
2. Provide an email
3. Click on 'Update'
4. Click on the link in the confirmation email sent by Violet Rails

**Expected behavior**
I should be able to confirm changes after going to the confirmation link

**Screenshots**

Changing account email:
![changing-email-from-admin](https://user-images.githubusercontent.com/73725297/213725200-15985b66-680f-4d05-ad3e-c090e6be256b.png)

Confirmation email sent by Violet Rails:
![link-to-confirm-email-change](https://user-images.githubusercontent.com/73725297/213726803-e871a7ed-27da-4aca-9592-f8e6daf1352c.png)

Invalid Token error:
![invalid-token-error](https://user-images.githubusercontent.com/73725297/213726768-ecd68023-79b3-4e83-9b04-23f62bb438f7.png)

**Desktop**
 - OS: Windows 10/11
 - Browser: Chrome 
 - Version: 109.0.5414.75

**Comment by donrestarone** [comment]
this is affecting nikean.org
