### ISSUE TITLE
investigate + fix why models are not being included/calculated in simplecov test coverage

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#245]

**Comment by donrestarone** [comment]
@Pralish this is the next infrastructure upgrade we are looking to do after we integrate the change for deploying to violet rails apps over Github Actions

**Comment by Pralish** [comment]
@donrestarone , I tracked it down to this line:

[  add_filter "app/models/"](https://github.com/restarone/violet_rails/blob/19507188f8ff91fa8aecce1d1f2c5f60eccb8fe4/test/test_helper.rb#L5)

This was done some 15 months ago. I removed  the line and models got included in simplecov test coverage. Do you remember why models were skipped before?

Before:

<img width="1356" alt="Screen Shot 2022-06-22 at 1 46 00 PM" src="https://user-images.githubusercontent.com/50227291/174976561-97aa17e1-9a35-4510-9898-ca5908670b00.png">

After:
<img width="1356" alt="Screen Shot 2022-06-22 at 1 46 17 PM" src="https://user-images.githubusercontent.com/50227291/174976737-5ca012fd-7648-4ab0-8eb4-0768ab077a40.png">
