### ISSUE TITLE
when a super admin user registers a subdomain they aren't given necessary permissions

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#284]
when a user is created by the system in this way, they are not assigned any privileges. We need to make sure that that they are given all privileges available in the system because they are the 1st user of the subdomain (and the subdomain creator because they are a super admin for the domain)

**Comment by donrestarone** [comment]
@Pralish can you look into this?

**Comment by Pralish** [comment]
@donrestarone , Here's the fix for this bug. Lemme know if they should also be given 'global_admin' role. 

https://github.com/restarone/violet_rails/pull/287
