### ISSUE TITLE
page preview broken for apex domains

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#288]
When a user clicks on the link for a CMS page, the URL is set incorrectly. Subdomains work as expected. 
![Screenshot from 2022-01-16 11-47-59](https://user-images.githubusercontent.com/35935196/149669426-a30d1beb-9312-4afc-a58e-638b746ce485.png)

**Comment by donrestarone** [comment]
@Pralish can you look into this?

**Comment by donrestarone** [comment]
@Pralish any updates?

**Comment by Pralish** [comment]
Hi Shashike,

Looking into it. Looks like the issue is coming from comfortable mexican
sofa. I will send a PR by Monday.

Thanks
