### ISSUE TITLE
[infra upgrade] use Capistrano action to automate blue green deployments External

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#294]

**Comment by Pralish** [comment]
https://github.com/Pralish/violet_rails/blob/test-staging/.github/workflows/deploy-staging.yml

Hi @donrestarone , Here's the branch I am experimenting with. I haven't been able to make capistrano-deploy work without setup-ruby. The error says:
> Error: Error: Unable to locate executable file: bundle.

https://github.com/Pralish/violet_rails/runs/5048056550?check_suite_focus=true

I will update you once I find something.

**Comment by donrestarone** [comment]
@Pralish is there a reason why we cant use `setup-ruby`?
