### ISSUE TITLE
Screenshots don't show up in Violet Rails client emails

### ISSUE THREAD

**Issue by Ayon95** [restarone/violet_rails#523]
Screenshots don't appear in Violet Rails client emails. Only the filename gets shown.
![Capture](https://user-images.githubusercontent.com/73725297/167172813-e1937b4e-8ff1-4a49-b5ee-6e7350218ce3.PNG)

**Comment by donrestarone** [comment]
this was due to an email where the client linked files inline that were attached separately (at the bottom)

**Comment by donrestarone** [comment]
@Ayon95 are we good to close this issue?

**Comment by Ayon95** [comment]
Yeah it can be closed
