### ISSUE TITLE
sanitize method/model definitions coming into Violet Rails of things like: Subdomain, Apartment, Tenant, switch, SomeModel.destroy_all, SomeModel.update_all, global_admin, can_manage_users

### ISSUE THREAD

**Issue by alis-khadka** [restarone/violet_rails#570]
We are using 'eval(#custom code)' in our code.
We need to implement a way to scrub method/model definitions coming into Violet Rails of things like: Subdomain, Apartment, Tenant, switch, Subdomain.destroy_all, Subdomain.update_all, global_admin, can_manage_users, -- so we can open this upto platform developers on subdomains instead of whole systems (like how we have it now, because of this vulnerability).

**Comment by donrestarone** [comment]
implement this as a before_save validation

**Comment by donrestarone** [comment]
# external_api_clients => model_definition

https://github.com/restarone/violet_rails/blob/master/app/models/api_action.rb#L64-L67
