### ISSUE TITLE
[Violet Rails Core]: Change scoping of api_clients and redirection after api_resource is deleted.

### ISSUE THREAD

**Issue by alis-khadka** [restarone/violet_rails#648]
![image](https://user-images.githubusercontent.com/25191509/171900369-349076d8-21f9-4c28-8fba-e316c03fe41c.png)
In the above image, the url gives the indication that the displayed api_clients are under a specific api_namespace. But, we are displaying all the api_clients in this page.
```ruby
# GET /api_clients or /api_clients.json
  def index
    @api_clients = ApiClient.all
  end
```

And the redirect is wrong too (we should remove the view that is rendered on the redirect after the user deletes an API resource).

**Comment by donrestarone** [comment]
https://api.rubyonrails.org/classes/ActionController/Redirecting.html#method-i-redirect_back

![Screenshot from 2022-06-06 20-50-01](https://user-images.githubusercontent.com/35935196/172272961-5228976f-512b-49bf-bc13-5d4e5b8421a2.png)
