### ISSUE TITLE
ability to receive web hooks (both authenticated and unauthenticated) and map them to External API Connections

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#682]
## Add drive strategy: web-hook to External API Connection
<img width="1728" alt="Screen Shot 2022-08-15 at 7 54 46 AM" src="https://user-images.githubusercontent.com/35935196/184630921-a73a3bea-09b7-477a-867b-e8f914f8fa81.png">

## Define a webhook endpoint for the API Namespace - Web-hook interface
Eg: POST request that must have the following attributes in the JSON payload 

``` javascript
{
  event: 'event_name_string_underscored',
  description: 'human readable description'
}
```
For every web hook triggered External API connection, list its interface under `Webhooks`
<img width="1137" alt="Screen Shot 2022-08-15 at 7 54 31 AM" src="https://user-images.githubusercontent.com/35935196/184630998-8d0a5f8b-d12a-49d0-a22a-e7c1c9bd3a35.png">

## Baked in Authentication (nice to have)
<img width="1159" alt="Screen Shot 2022-08-15 at 7 55 47 AM" src="https://user-images.githubusercontent.com/35935196/184631988-defa3fb6-b948-4100-957a-2f349f98eaeb.png">
<img width="1118" alt="Screen Shot 2022-08-15 at 7 55 34 AM" src="https://user-images.githubusercontent.com/35935196/184631990-57bc03ba-89df-4c35-bb33-b766c1f6e66a.png">

Rename API Clients => API Keys. Decouple API Clients (API Keys) from the REST interface and the API Namespace. Allow API Clients (API Keys) to be issued and be associated with many API Namespaces

**Comment by Pralish** [comment]
@donrestarone , What is event in this payload?

```
{
  event: 'event_name_string_underscored',
  description: 'human readable description'
}
```

**Comment by donrestarone** [comment]
@Pralish the event name is a unique identifier in case an endpoint needs to handle different scenarios 


Eg: event for failed transactions vs successful ones 

See Stripe webhook docs: https://stripe.com/docs/webhooks

We are looking to support a service like that (with web hook authentication and events)
