### ISSUE TITLE
fix data discovery issue in rake tasks (public schema is not accessed)

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#692]
I am exploring a hotfix here: https://github.com/restarone/violet_rails/pull/686/files#diff-bff8182f3a99c39531f1db7b69790c3b38596cb871726bd02088776c73c289be

**Comment by Ayon95** [comment]
Can you provide some more context? What's the expected behavior? Also, you mentioned a hotfix. Did it work?
