### ISSUE TITLE
nikean.orgpasswords#create (ActionView::MissingTemplate) "Missing template users/passwords/create, users/passwords

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#783]
``` txt
An ActionView::MissingTemplate occurred in passwords#create:

  Missing template users/passwords/create, users/passwords/create, devise/passwords/create, devise/create, application/create with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder, :haml]}. Searched in:
  * "/var/www/violet/releases/20220619182518/app/views"
  * "/var/www/violet/shared/bundle/ruby/2.6.0/gems/ember-cli-rails-0.10.0/app/views"
  * "/var/www/violet/shared/bundle/ruby/2.6.0/gems/graphiql-rails-1.8.0/app/views"
  * "/var/www/violet/shared/bundle/ruby/2.6.0/gems/devise_invitable-2.0.3/app/views"
  * "/var/www/violet/shared/bundle/ruby/2.6.0/bundler/gems/simple_discussion-ccc76a485221/app/views"
  * "/var/www/violet/shared/bundle/ruby/2.6.0/bundler/gems/comfy-blog-767f3848165a/app/views"
  * "/var/www/violet/shared/bundle/ruby/2.6.0/bundler/gems/comfortable-mexican-sofa-456fb8507e96/app/views"
  * "/var/www/violet/shared/bundle/ruby/2.6.0/gems/devise-4.7.3/app/views"
  * "/var/www/violet/shared/bundle/ruby/2.6.0/gems/actiontext-6.1.5/app/views"
  * "/var/www/violet/shared/bundle/ruby/2.6.0/gems/actionmailbox-6.1.5/app/views"
```

**Comment by Pralish** [comment]
## RCA

I have narrowed the issue down to this line on devise gem.

https://github.com/heartcombo/devise/blob/f8d1ea90bc328012f178b8a6616a89b73f2546a4/lib/devise/controllers/helpers.rb#L264


### Issue:

The request format is turbo_stream. It should have been html. Not sure when it started happening. This was suppose to happen after rails 7. But devise didn't recognize turbo_stream as navigational format.

I found there was a open PR to fix this on devise:
https://github.com/heartcombo/devise/pull/5340

**Actual**
<img width="358" alt="Screen Shot 2022-06-21 at 7 24 55 PM" src="https://user-images.githubusercontent.com/50227291/174814357-55457381-8246-4048-94f7-afa200cac830.png">

**Expected**
<img width="410" alt="Screen Shot 2022-06-21 at 7 21 16 PM" src="https://user-images.githubusercontent.com/50227291/174814629-3bb18b11-80ee-48c9-934e-23d4381cf016.png">

### Solution

Add 'turbo_stream' to list of navigational_formats on devise config.

https://github.com/restarone/violet_rails/pull/787

### References:

- https://github.com/heartcombo/devise/issues/5446#issuecomment-1003114003
- https://github.com/heartcombo/devise/pull/5340
- https://github.com/heartcombo/devise/pull/5340/files [Open PR on Devise to fix this issue]
