### ISSUE TITLE
REST API and GQL does not return non primitive types (richtext and file)

### ISSUE THREAD

**Issue by donrestarone** [restarone/violet_rails#875]
**Describe the bug**

The REST API and GQL should include non primitive type fields in the response. 

**To Reproduce**
Given an API Namespace like the following: 

![Screenshot from 2022-07-05 10-42-23](https://user-images.githubusercontent.com/35935196/177355570-309319be-3b06-4fdd-8b30-72e0c33f52f6.png)

the system does not include rich text strings in the REST API response: 

![Screenshot from 2022-07-05 10-42-11](https://user-images.githubusercontent.com/35935196/177357012-96811aad-041c-429a-974f-146c98e5fbb9.png)

you can see the Graph and REST interfaces here:

![Screenshot from 2022-07-05 10-43-58](https://user-images.githubusercontent.com/35935196/177357038-982d6ce9-c298-4f10-a413-60deb191ae60.png)

**Expected behavior**

For rich text the system should return a string under the respective attribute and for a file it should be a rails/activestorage generated URL.

**Comment by Pralish** [comment]
**Upgrade to latest version of describe api**

- use response['data']['attributes'] instead of just response
