### ISSUE TITLE
Recaptcha success handler activates Submit button of all forms on a page

### ISSUE THREAD

**Issue by Ayon95** [restarone/violet_rails#978]
Currently, when recaptcha success handler gets called, it goes through the Submit button of each form and enables it. It would be better if the success handler can be scoped within the form it's connected to.

For example, if recaptcha is solved for Form A, then the success handler will enable the Submit button of only that form. It will keep other forms untouched.

Perhaps, something like this could work:
```js
function ctaSuccessHandler(form) {
  const submitButton = form.querySelector('input[type="submit"]');
  submitButton.removeAttribute("disabled");
}
```
This implementation relies on passing the form as an argument when ctaSuccessHandler is called.

**Comment by donrestarone** [comment]
In the case below (recaptcha V2) we observe that the submit button is not locked when the challenge is not completed

<img width="1728" alt="Screen Shot 2022-07-30 at 1 25 21 PM" src="https://user-images.githubusercontent.com/35935196/181934797-991fb86d-3f96-4642-b1a9-4326adce2216.png">

We expect the submit to be locked until recaptcha v2 is solved. 

Caveats: @Pralish  noted that there is another form (recaptcha v3) in the footer, so its possible that the success handler for that form is unblocking the submit button on the recaptcha v2 form (illustrated above)

**Comment by donrestarone** [comment]
In the practical case below, we should show a red colored label below the recaptcha V2 challenge and above the submit button that says "Please complete reCAPTCHA" 
https://user-images.githubusercontent.com/35935196/181936077-089fc51b-1e8f-44e1-b72f-7561399d943f.mov
